name: simple-projects
channels:
  - defaults
dependencies:
  - python=3.9
  - varname
  - ipykernel
  - tornado
  - traitlets
  - pure_eval
  - sqlite
  - nest-asyncio
  - pickleshare
  - pywin32
  - ipython
  - executing
  - zeromq
  - vs2015_runtime
  - typing_extensions
  - importlib_metadata
  - packaging
  - pyzmq
  - openssl
  - wcwidth
  - importlib-metadata
  - jedi
  - parso
  - setuptools
  - python-dateutil
  - psutil
  - prompt-toolkit
  - decorator
  - platformdirs
  - libsodium
  - pygments
  - vc
  - jupyter_core
  - six
  - debugpy
  - backcall
  - tzdata
  - colorama
  - asttokens
  - ca-certificates
  - wheel
  - zipp
  - stack_data
  - comm
  - pip
  - jupyter_client
  - matplotlib-inline
  - numpy
  - scipy
